### ISSUE TITLE
please tag 1.0

### ISSUE THREAD

**Issue by smcv** [mvo5/unattended-upgrades#105]
@rbalint released unattended-upgrades 1.0 to Debian, but it isn't tagged here. I *think* the right place for the tag is commit fd761dc00b35e832e920e87732d84590be9fffe9 or (equivalently) merge commit c02ea0a42ae8c4c99781f3479f9340dd9777ff29 (#100).

Since this is a "native" Debian package, ideally whoever does the upload to Debian would also push the tag here.

**Comment by rbalint** [comment]
@smcv Thanks, I prepared the tag just forgot to push it

**Comment by rbalint** [comment]
(until now)
