### ISSUE TITLE
Allow mail subject personalization

### ISSUE THREAD

**Issue by smortex** [mvo5/unattended-upgrades#107]
When receiving mail from nodes which have the same host name but have different domain names (e.g. *foo.example.com* and *foo.bar.example.net*), the subject of the message only contains the host part of the FQDN (in this example `Subject: unattended-upgrades result for 'foo'`) which makes it harder to distinguish these hosts.

While you can refer to the sender to find out which node has sent the message, it might be convenient for the user to have the FQDN in the mail title, or maybe even personalize this title with some configuration settings (i.e. when the config is generated by configuration management tools, the subject could include a customer ID).

Do you have an opinion about this?

**Comment by rbalint** [comment]
It would be nice, indeed and #104 also asks for email customization. I don't plan implementing this in the near future but patches are welcome.

**Comment by mc-hack** [comment]
I've the same problem as smortex.  In the script unattended-upgrade at line 910-912 you resolve senders hostname with python function os.uname. As the python reference says, the better way would be using the socket.hostname function:

https://docs.python.org/2/library/os.html#os.uname

So a patch could be

`
def host():
    # type: () -> str
    return socket.gethostname()
`
D'core?
