### ISSUE TITLE
Run tests only against python3?

### ISSUE THREAD

**Issue by irregulator** [mvo5/unattended-upgrades#113]
Hi,

While I was working on a patch and ran the tests I noticed that since `de1d61a707a539` tests are run with both python2 and python3. As my intention was to use a python3 feature (subprocess.run()) in the patch, tests were actually failing.

Given that the two executables `unattended-upgrade` and `unattended-upgrade-shutdown` already feature a python3 shebang, would it be safe to assume that this is a python3 only project? Equally important: may we introduce code that strictly depends on python3?

If so, I would suggest to modify `test/Makefile` so as tests are only executed with python3. In fact I verified that tests are actually passing if [python2 is removed](https://github.com/irregulator/unattended-upgrades/commit/f8786231e80b0f5ec64d462983e7e6182df6e382). Shall I submit a relevant pull request?

Thanks for developing this software,

**Comment by rbalint** [comment]
I'm about to drop Python 2 support including from test in my next PR.

**Comment by irregulator** [comment]
Thanks
