### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by truber** [mvo5/unattended-upgrades#13]
Mit 
Ubuntu 14.04.3 LTS 
und 
lrwxrwxrwx 1 root root       9 Mär 23  2014 python3 -> python3.4 
bekommen wir das folgende error-mail: 

/etc/cron.daily/apt:
Exception: unsupported operand type(s) for %: 'bytes' and 'tuple'
Traceback (most recent call last):
  File "/usr/bin/unattended-upgrade", line 1435, in <module>
    main(options)
  File "/usr/bin/unattended-upgrade", line 1382, in main
    pkgs, pkg_install_success, pkgs_kept_back, mem_log, log_content)
  File "/usr/bin/unattended-upgrade", line 815, in send_summary_mail
    host(), res)
TypeError: unsupported operand type(s) for %: 'bytes' and 'tuple'

**Comment by mvo5** [comment]
Thanks for your bugreport.

What version of unattended-upgrades are you using? I.e., what does:

    $ apt list unattended-upgrades

show?

**Comment by truber** [comment]
$ apt list unattended-upgrades
Listing... Fertig
unattended-upgrades/trusty-updates,trusty-security,now 0.82.1ubuntu2.3 all [installed]

**Comment by truber** [comment]
/usr/bin/unattended-upgrade
.......
def host():
    return os.uname()[1]
.......
        subject = _("unattended-upgrades result for '%s': '%s'") % (
            host(), res)

https://docs.python.org/3/library/os.html#os.uname
Changed in version 3.3: Return type changed from a tuple to a tuple-like object with named attributes.
Wurde das berücksichtigt, ist das script jemals auf python3.4 gelaufen ?

**Comment by mvo5** [comment]
I have a python3.4 install here and I can not reproduce the error - if you can reproduce it and always get it, I would love a simple "print(res)" and "print(host())" debug statement in the line before the error happens. If you could do that and paste the output here, that would be super-helpful. Thanks!

**Comment by truber** [comment]
We don't get the error on each machine with Ubuntu 14.04.3 LTS. 
Perhaps on some machines not all is neat and clean. 
We have solved the problem with colon in filenames with a filesystem change (ntfs to ext4). 
We are using now again our original script.
