### ISSUE TITLE
Upgrade needs new packages to be installed

### ISSUE THREAD

**Issue by SantjagoCorkez** [mvo5/unattended-upgrades#146]
That's unclear after reading the docs if u-u will silently install new packages if they become an update's new dependency or the u-u will stop right at the moment a new package requirement is met.

If former, should it be a configurable behavior then?

For example:
My own environment suffers of lack of driver support (NVidia GF GTX 1050M). Either nouveau or proprietary newest driver set available ATM lead the system to become not operatable at all if installed. Neither helps bumblebee. So I have to stick to i915 device set thanks I'm don't need 3D at all.

I've just noticed such a thing:
```$ sudo apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following NEW packages will be installed:
  libxnvctrl0
```
I've looked through the information on this new package and got it's NVidia related. So, to keep my system safe from any NVidia support at all I need to find out how to exclude this package from the to-be-installed list. That led to a package I don't consider of any use to me. So I've just removed the reverse-dependency to that `libxnvctrl0`

But if that upgrade were unattended. Would the new dependency then be installed silently? What if then a couple of updates later a new dependency to nvidia kernel/Xorg driver appears? Will it make my system a boot-to-a-hang again?

**Comment by rbalint** [comment]
New dependencies are pulled in from allowed origins, but u-u honors kept packages (see apt-mark(8)) and u-u also allows blacklisting packages (see the example configuration file).
If those are not enough you can use equivs: https://wiki.debian.org/Packaging/HackingDependencies

**Comment by SantjagoCorkez** [comment]
Well, though a report/issue is closed still can't agree it's the desired behavior:

I can't know of any **new** dependency a package update will or won't declare. The methods you point at are of hacking of situations being known beforehand. In a case of there weren't a new declared dependency at all before, for example a version bump of an installed package I can't mask/blacklist that new dependency.

Well then this is still up to you to rule your project. Still can't get used to the fact linux is all about dirty hacks.

**Comment by rbalint** [comment]
Disabling new package installations can easily prevent installing other security updates unrelated to the drivers you have problems with. IMO the tools are already available for holding back packages and I don't consider blacklists (note that you can use Python regex there) or apt marks hacks. For equivs, well, that's admittedly a hack but I just mentioned it because it can be a very good fit for your problem.
