### ISSUE TITLE
/etc/kernel/postinst.d/unattended-upgrades doesn't create/update /run/reboot-required.pkgs

### ISSUE THREAD

**Issue by michael-schaller** [mvo5/unattended-upgrades#150]
/etc/kernel/postinst.d/unattended-upgrades doesn't create/update /run/reboot-required.pkgs. This means that it is harder than necessary for an user to figure out which kernel package has triggered a reboot notification.

**Comment by michael-schaller** [comment]
Looking at this some more it would probably be best to also not trigger a reboot notification if /etc/kernel/postinst.d/reboot-notifier exists as that already handles the reboot notification.

**Comment by rbalint** [comment]
Fixed in https://github.com/mvo5/unattended-upgrades/pull/158
