### ISSUE TITLE
Conflicts should mark the run as unsuccessful

### ISSUE THREAD

**Issue by zerkms** [mvo5/unattended-upgrades#165]
A few days ago `initramfs-tools` packages was upgraded with a security release.

The new version brings the following restriction: `Breaks netplan.io (<< 0.36.2)`

It is currently `netplan.io` version `0.36.1` installed on the system.

And it's not in the `initramfs-tools` dependencies.

The log:

```
2019-01-08 20:19:23,221 INFO Initial whitelisted packages:
2019-01-08 20:19:23,222 INFO Starting unattended upgrades script
2019-01-08 20:19:23,222 INFO Allowed origins are: o=Ubuntu,a=bionic-security
2019-01-08 20:19:53,530 WARNING package initramfs-tools-bin upgradable but fails to be marked for upgrade (E:Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.)
2019-01-08 20:19:54,034 WARNING package initramfs-tools-core upgradable but fails to be marked for upgrade (E:Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.)
```

And `unattended-upgrades` configured with `Unattended-Upgrade::MailOnlyOnError "true";` yet I did not receive an email (while I do when a genuine error happens).

I think this warning should be promoted to errors and reported correspondingly.

**Comment by rbalint** [comment]
As a result of this Breaks relationship initramfs-tools is held back. Packages are held back for other reasons like changed configuration files and MailOnlyOnError "true"; prevents you from getting notified about those situations as well, thus not treating this case as error is consistent with that other case.

Please also note that MailOnlyOnError "false"; is the default and "true" is not recommended.

OTOH and option would be useful where u-u would send email only when an action is needed, like when packages are held back, failed to properly install or a reboot is required.

**Comment by zerkms** [comment]
> Packages are held back for other reasons like changed configuration files

regardless of the reasons - `unattended-upgrades` is instructed to install security updates. For me as an administrator only a successful installation is a successful outcome, everything else is an error, since the state of the system is not desired.

**Comment by rbalint** [comment]
@zerkms security updates can be held back via blacklisting or apt-mark-ing packages to keep. In those cases held packages are held back by the administrator's configuration and IMO those case would not qualify as errors.
The problem you faced also should not occur when using only official Ubuntu packages thus I reported it here:
https://bugs.launchpad.net/ubuntu/+source/initramfs-tools/+bug/1811210

**Comment by zerkms** [comment]
Okay. I'm monitoring a list of available but not installed packages, so it does not affect me directly.

But yep, subscribed to the launchpad bug.

Thanks :-)
