### ISSUE TITLE
Add the option to send to syslog on Ubuntu 16.04?

### ISSUE THREAD

**Issue by junior466** [mvo5/unattended-upgrades#167]
Pardon my ignorance as I can’t find the answer after hours of searching. I’ve noticed that my install of unattended upgrades on Ubuntu 18.04 has the option to send to syslog but that option doesn’t exist on 16.04. 

Is my only option to upgrade Ubuntu?

**Comment by rbalint** [comment]
There is a full backport of u-u in flight for 16.04:
https://bugs.launchpad.net/ubuntu/+source/unattended-upgrades/+bug/1702793

Testing is welcome and it includes this feature.
