### ISSUE TITLE
how to blacklist kernel updates?

### ISSUE THREAD

**Issue by Deihmos** [mvo5/unattended-upgrades#181]
Can anyone tell me how you can blacklist kernel updates on Ubuntu 18.04? Is it "linux-generic";?

**Comment by rbalint** [comment]
May I ask why you want to do that?

Those configuration files are good starting point, but since this is highly recommended against I don't plan writing a guide to do it.

```
/etc/apt/apt.conf.d/01autoremove-kernels
/etc/apt/apt.conf.d/01autoremove
```

**Comment by Deihmos** [comment]
I wanted livepatch to update the kernel but changed my mind.

**Comment by rbalint** [comment]
OK, livepatch can save _some_ reboots but can't fix all potential kernel problems without a reboot.
