### ISSUE TITLE
missing documentation

### ISSUE THREAD

**Issue by seamusdemora** [mvo5/unattended-upgrades#183]
I've just installed `unattended-upgrades` on my Raspberry Pi system (Raspbian OS). My first step was to preuse the documentation, but `man unattended-upgrades` yielded nothing. 

Also, `unattended-upgrade -h` suggests there's no version number to report. 

DId I get a flawed package?

**Comment by rbalint** [comment]
Please try `man unattended-upgrade`. There is also the README in the standard location, /usr/share/doc/unattended-upgrades/README.md.gz

**Comment by seamusdemora** [comment]
Ooops :)

**Comment by seamusdemora** [comment]
$ sudo apt-get install ***unattended-upgrade***
Reading package lists... Done
Building dependency tree       
Reading state information... Done
***E: Unable to locate package unattended-upgrade***
$ sudo apt-get install ***unattended-upgrades***
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  bsd-mailx mail-transport-agent needrestart
The following NEW packages will be installed:
  ***unattended-upgrades***
$ man ***unattended-upgrades***
No manual entry for ***unattended-upgrades***
$ man ***unattended-upgrade***
:) 

Seems odd, but maybe that's just me.  Thanks for the tip.
