### ISSUE TITLE
raspbian has no `reboot-required` file

### ISSUE THREAD

**Issue by seamusdemora** [mvo5/unattended-upgrades#184]
> - Unattended-Upgrade::Automatic-Reboot - boolean (default:False)

> Automatically reboot WITHOUT CONFIRMATION if the file /var/run/reboot-required is found after the upgrade.
 
Unfortunately, Raspbian (the Raspberry Pi default OS) does not generate the `reboot-required` file. Raspbian aliases `/var/run` to `/run`, and it's not created in either place. 

Is there any other way to test for the necessity of a reboot?

**Comment by seamusdemora** [comment]
It's just occurred to me after reading another issue: Does this package (`unattended-upgrades`) generate the `reboot-required` file?

**Comment by rbalint** [comment]
The file is created in /etc/kernel/postinst.d/unattended-upgrades which is being run on kernel updates.
Other packages can create it as well. Please ask Rasbpbian-specific questions at Raspbian support, the package may have distro-specific changes.
