### ISSUE TITLE
Typo in message

### ISSUE THREAD

**Issue by hablutzel1** [mvo5/unattended-upgrades#197]
https://github.com/mvo5/unattended-upgrades/blob/c41731e30c39bb121b0572a23e43c7e476c531c5/unattended-upgrade#L1304

Says:

> This should never be reached, if we are here we either have sendmail or mailx. ...

But I think there should say:

> This should never be reached, if we are here we neither have sendmail nor mailx. ...

**Comment by rbalint** [comment]
Because of:

https://github.com/mvo5/unattended-upgrades/blob/c41731e30c39bb121b0572a23e43c7e476c531c5/unattended-upgrade#L1236

"if we are here we either have sendmail or mailx", so both of the messages are correct and incorrect at the same time and this is why they describe an impossible situation.

**Comment by hablutzel1** [comment]
Thanks, I didn't see that previous validation.

Nevertheless, the following message is not strictly correct:

https://github.com/mvo5/unattended-upgrades/blob/c41731e30c39bb121b0572a23e43c7e476c531c5/unattended-upgrade#L1304

Because in that right moment, the "here" word refers to the `else` block. 

Now, reaching that section is not totally impossible, because the initial validation in https://github.com/mvo5/unattended-upgrades/blob/c41731e30c39bb121b0572a23e43c7e476c531c5/unattended-upgrade#L1236 could have passed and immediately after that the binaries could have been deleted making the script reach 

https://github.com/mvo5/unattended-upgrades/blob/c41731e30c39bb121b0572a23e43c7e476c531c5/unattended-upgrade#L1303

Finally, I think that the following message would be more appropriate for the `AssertionError`:

> "This should never be reached as we previously validated that we either have sendmail or mailx. Maybe they've been uninstalled in this right moment?".

**Comment by rbalint** [comment]
@hablutzel1 Since u-u keeps the lock to the packaging system the binaries should not disappear between the two checks. Probably no one ever saw this error being thrown. If you really think the wording should be fixed then please open a PR with the fix.

**Comment by hablutzel1** [comment]
> @hablutzel1 Since u-u keeps the lock to the packaging system the binaries should not disappear between the two checks.

But `MAIL_BINARY` or `SENDMAIL_BINARY` could always be manually removed, very improbable, but possible, isn't it?.

> Probably no one ever saw this error being thrown. If you really think the wording should be fixed then please open a PR with the fix.

Done, #208 .
