### ISSUE TITLE
Updates sometimes not installed by unattended-upgrades-shutdown

### ISSUE THREAD

**Issue by Yvan-Masson** [mvo5/unattended-upgrades#229]
Hi,

I configured a few Debian 10 desktops to upgrade automatically during shutdown. It worked at the beginning, but not anymore. Fortunately, I can reproduce the issue in a test VM with snapshots. I could not find anything related in the upstream changelog, that is why I submit this issue here and not in the Debian bugtracker.

`/etc/apt/apt.conf.d/51unattended-upgrades-local` contains my settings:
```
Unattended-Upgrade::Origins-Pattern {
  "origin=Debian,codename=buster-updates";
  "origin=Debian,codename=buster,label=Debian";
  "origin=Debian,codename=buster,label=Debian-Security";
};
Unattended-Upgrade::MinimalSteps "false";
Unattended-Upgrade::InstallOnShutdown "true";
Unattended-Upgrade::Verbose "true";
Unattended-Upgrade::Debug "true";
```
`/etc/apt/apt.conf.d/10periodic`:
```
APT::Periodic::Unattended-Upgrade "1";
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Download-Upgradeable-Packages "1";
APT::Periodic::AutocleanInterval "7";
```
`/etc/systemd/logind.conf`:
```
InhibitDelayMaxSec=600
```
Logs are attached. Note that `/var/log/unattended-upgrades/unattended-upgrades-dpkg.log` is empty.
[unattended-upgrades.log](https://github.com/mvo5/unattended-upgrades/files/3728408/unattended-upgrades.log)
[unattended-upgrades-shutdown.log](https://github.com/mvo5/unattended-upgrades/files/3728409/unattended-upgrades-shutdown.log)

If I do "some" updates manually, unattended-upgrades install the remaining ones perfectly. From my tests, I can say that:
- the issue does not come from the number of upgrades available
- the issue does not come from a particular package upgrade

Do not hesitate to ask if you need more info or if you want me to do some tests.

Regards,
Yvan

**Comment by rbalint** [comment]
This seems to be the same issue as:
https://bugs.launchpad.net/ubuntu/+source/unattended-upgrades/+bug/1843099

**Comment by Yvan-Masson** [comment]
Thanks for your answer. It can't tell if it the same bug. Mine is easily reproducible: depending of what packages I manually install, unattended-upgrades-shutdown runs or not. For now, I have two different combinations of packages that once installed will "re-enable" unattended-upgrades.

**Comment by Yvan-Masson** [comment]
I re-read your link: if I understand well, it should be enough to increase `InhibitDelayMaxSec` in `/etc/systemd/logind.conf` (which I already did). Am I right? Or is this not sufficient?

**Comment by rbalint** [comment]
In general it should be enough, but there may be cases with a lot of not installable packages, where it is not. :-( I'm checking how the situation could be improved.

**Comment by Yvan-Masson** [comment]
OK thanks for the clarification. Do not hesitate to ask if you want me to do some tests.

**Comment by Yvan-Masson** [comment]
Thanks for the work on this issue.

I tested the new 1.15 on my test VM, but unfortunately it does not fix the issue. Maybe I forgot something, so here is what I did:
- downloaded `unattended-upgrade` and `unattended-upgrade-shutdown` scripts from GitHub, to replace `/usr/bin/unattended-upgrade` and `/usr/share/unattended-upgrade/unattended-upgrade-shutdown` on my system (Debian stable)
- ran `unattended-upgrade -d`
- shutdown the system (with the mouse, not with `poweroff`)

As before, there is nothing interesting in `/var/log/unattended-upgrades/unattended-upgrade-shutdown`.

Do not hesitate to ask if needed.

Regards,
Yvan

**Comment by rbalint** [comment]
Looking at the original issue, in your logs the first sigterm is received after ~30 seconds:
```
2019-10-11 16:36:26,213 INFO Initial blacklist : 
...
2019-10-11 16:36:54,874 WARNING SIGTERM received, will stop
```
Indicating, that the
```
InhibitDelayMaxSec=600
```
is still overridden by the setting in `/usr/lib/systemd/logind.conf.d/unattended-upgrades-logind-maxdelay.conf` :
```
[Login]
# delay
InhibitDelayMaxSec=30
```

If you bump the delay to 30 mins as suggested in `/usr/share/doc/unattended-upgrades/NEWS.Debian.gz` it will work.

**Comment by Yvan-Masson** [comment]
Please apologize, it seems I had read `logind.conf` manpage too fast and missed the sentence `The main configuration file is read before any of the configuration directories, and has the lowest precedence;`. With a proper override, updates work.

Many thanks for the help!
