### ISSUE TITLE
"MinimalSteps" description should take into account unattended-upgrade-shutdown

### ISSUE THREAD

**Issue by Yvan-Masson** [mvo5/unattended-upgrades#230]
Hi,

Currently, inline explanation of `MinimalSteps` option is:
```
// Split the upgrade into the smallest possible chunks so that
// they can be interrupted with SIGTERM. This makes the upgrade
// a bit slower but it has the benefit that shutdown while a upgrade
// is running is possible (with a small delay)
//Unattended-Upgrade::MinimalSteps "true";
```
This description and the default value are great for online updates. However, it could be great to explain that it should be usually set to `false` when combined with `Unattended-Upgrade::InstallOnShutdown "true";`: people might not understand at first that by default that this setting affects updates even when applied during shutdown.

For example, you could add something like "When "Unattended-Upgrade::InstallOnShutdown" is "true", you should set this option to "false" to apply all updates in one go."  (note that I am not an English native).

Thanks for your time and work,
Yvan

**Comment by rbalint** [comment]
No, even if you use InstallOnShutdown  keeping MinimalSteps set to true is the safe choice, since if the upgrade takes too long systemd can time out and kill dpkg in the middle of the upgrade.

**Comment by Yvan-Masson** [comment]
Your are right, it is the safest choice. I completely respect your decision, but I think I did not explain properly my thoughts so I will try to do it one last time.

This is safe, but it also means that upgrades are almost never done in one time: systemd sends SIGTERM even before upgrades begin, so only one chunk of updates is done in one shutdown. So if the computer is not started often enough, it will never be able to install all pending updates (which are often security updates).

On the other hand (but I might be wrong), once systemd/logind is configured as explained (InhibitDelayMaxSec=1800), there is very little probability that the upgrade is longer than 30 minutes, and killed by systemd.

Regards,
Yvan
