### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by elig0n** [mvo5/unattended-upgrades#241]
When upgrading via pip it complains:

`Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/unattended-upgrades/`

**Comment by rbalint** [comment]
@elig0n I'm not sure why you wanted to upgrade unattended-upgrades via `pip` since it is not available via `pip` AFAIK.

**Comment by elig0n** [comment]
@rbalint I upgraded all my pip packages and this happened

**Comment by rbalint** [comment]
This sounds like a `pip` bug. A way of reproducing it may be interesting, mostly for pip maintainers though.
