### ISSUE TITLE
Lots of messages related to unattended-upgrades are logged in the journal

### ISSUE THREAD

**Issue by bbinet** [mvo5/unattended-upgrades#242]
Unattended-upgrades seem to try to activate the systemd-logind service which is masked in my headless system, so I see the below log messages in systemd journal:

```
$ journalctl -xe | tail -6
Jan 14 08:55:18 enerwhere-mc-7 dbus-daemon[222]: [system] Activating via systemd: service name='org.freedesktop.login1' unit='dbus-org.freedesktop.login1.service' requested by ':1.1' (uid=0 pid=181 comm="/usr/bin/python3 /usr/share/unattended-upgrades/un")
Jan 14 08:55:18 enerwhere-mc-7 dbus-daemon[222]: [system] Activation via systemd failed for unit 'dbus-org.freedesktop.login1.service': Unit systemd-logind.service is masked.
Jan 14 08:55:19 enerwhere-mc-7 dbus-daemon[222]: [system] Activating via systemd: service name='org.freedesktop.login1' unit='dbus-org.freedesktop.login1.service' requested by ':1.1' (uid=0 pid=181 comm="/usr/bin/python3 /usr/share/unattended-upgrades/un")
Jan 14 08:55:19 enerwhere-mc-7 dbus-daemon[222]: [system] Activation via systemd failed for unit 'dbus-org.freedesktop.login1.service': Unit systemd-logind.service is masked.
Jan 14 08:55:20 enerwhere-mc-7 dbus-daemon[222]: [system] Activating via systemd: service name='org.freedesktop.login1' unit='dbus-org.freedesktop.login1.service' requested by ':1.1' (uid=0 pid=181 comm="/usr/bin/python3 /usr/share/unattended-upgrades/un")
Jan 14 08:55:20 enerwhere-mc-7 dbus-daemon[222]: [system] Activation via systemd failed for unit 'dbus-org.freedesktop.login1.service': Unit systemd-logind.service is masked.
```

```
$ systemctl status systemd-logind.service
● systemd-logind.service
   Loaded: masked (Reason: Unit systemd-logind.service is masked.)
   Active: inactive (dead)
```

- are these messages harmless? (will unattented-upgrade still work normally without systemd-logind service running?)
- how could I prevent this log messages to be sent to the systemd journal every second?

**Comment by rbalint** [comment]
Unattended-upgrades will perform the updates without systemd-login running, but shutdowns in the middle of performing upgrades may break the system because u-u relies on systemd-logind to gracefully shut down _before_ the shutdown transaction is started by systemd.

For more details please see:
https://www.freedesktop.org/wiki/Software/systemd/inhibit/

**Comment by bbinet** [comment]
So if systemd-logind.service is masked, I can also mask unattended-upgrades.service if this service is used only for the graceful shutdown part, right?

Will unattended-upgrades continue to be applied even is unattended-upgrades.service is not running?

**Comment by rbalint** [comment]
@bbinet Yes, it can be disabled, while I did not want to point to that direction. The application of updates are performed by apt-daily-upgrade.service .

**Comment by bbinet** [comment]
@rbalint ok, thank you
