### ISSUE TITLE
DPkg::Pre-Invoke and DPkg::Post-Invoke called on almost every package

### ISSUE THREAD

**Issue by szepeviktor** [mvo5/unattended-upgrades#273]
_New_ servers with Debian buster with unattended-upgrades v1.11.2 seems to be calling DPkg::Pre/Post-Invoke at every package upgraded.

apt v1.8.2, sysvinit (no systemd)

I run monit stop/start at these hooks
https://github.com/szepeviktor/debian-server-tools/blob/b93dc9937d458429f992088429f6e8471378d057/monitoring/monit/monit-debian-setup.sh#L191-L194
and it starts and stops very many times.

![kép](https://user-images.githubusercontent.com/952007/81602401-d555c180-93cc-11ea-967c-13b3c7f25719.png)

Please advise.
Thanks.

**Comment by szepeviktor** [comment]
Could `Unattended-Upgrade::MinimalSteps "true";` cause this?

**Comment by rbalint** [comment]
Yes.

**Comment by rbalint** [comment]
It is not called on every package, but on every minimal set of packages that can be installed/upgraded, but most often this is a single package.

**Comment by szepeviktor** [comment]
Thank you @rbalint !!

**Comment by rbalint** [comment]
See also https://github.com/mvo5/unattended-upgrades/issues/266

**Comment by szepeviktor** [comment]
for googlers:

```bash
sed -i -e 's#.*\(Unattended-Upgrade::MinimalSteps "true";\)\s*$#\1#' /etc/apt/apt.conf.d/50unattended-upgrades
```
