### ISSUE TITLE
[featurerequest] Automatic-Reboot on certain days of the week

### ISSUE THREAD

**Issue by arthurlogilab** [mvo5/unattended-upgrades#274]
First of thanks a bunch for unattended-upgrades which we've been happily using for years ! 

We're looking into using `Automatic-Reboot` but since our sysadmin team doesn't work weekends we'd like to activate the automatic reboot on certain week days (and during office hours so we can fix any problems) : 

```
Unattended-Upgrade::Automatic-Reboot "true";
Unattended-Upgrade::Automatic-Reboot-Time "10:00";
```

Would be changed to something like : 

```
Unattended-Upgrade::Automatic-Reboot "true";
Unattended-Upgrade::Automatic-Reboot-Time "10:00";
Unattended-Upgrade::Automatic-Reboot-DayOfTheWeek "tuesday";
```

**Comment by rbalint** [comment]
Please see #263 , this is a subset of that issue.
