### ISSUE TITLE
Packages getting auto removed when not configured to

### ISSUE THREAD

**Issue by nacholopez** [mvo5/unattended-upgrades#276]
Hi,

I'm not sure sure if I'm missing something but I have the following on the logs even though I have the removal of unused dependencies disabled:
```
2020-05-29 06:13:50,234 INFO Packages that are auto removed: 'authbind ca-certificates-java default-jre-headless .....
```

```
$ apt-config dump | grep -i ^Unatt
Unattended-Upgrade "";
Unattended-Upgrade::Allowed-Origins "";
Unattended-Upgrade::Allowed-Origins:: "${distro_id}:${distro_codename}";
Unattended-Upgrade::Allowed-Origins:: "${distro_id}:${distro_codename}-security";
Unattended-Upgrade::Allowed-Origins:: "${distro_id}ESM:${distro_codename}";
```

This seems to have been a one time thing without any config changes.
System is ubuntu xenial running `unattended-upgrades              0.90ubuntu0.10`

Thanks.

**Comment by rbalint** [comment]
Please use latest version from xenial-updates, `1.1ubuntu1.18.04.7~16.04.6`
