### ISSUE TITLE
[Feature Request] Package White List

### ISSUE THREAD

**Issue by zero77** [mvo5/unattended-upgrades#79]
Can you please add a white list option where any package name that is in the list is also automatically updated.
Thanks

**Comment by 6uhrmittag** [comment]
hi!
It is easy to overlook, but it's already in there:
```
Example:

Unattended-Upgrade::Package-Whitelist {
   "bash";
};
```

One downside:
```
Unattended-Upgrade::Allowed-Origins {
   "${distro_id}:${distro_codename}-security";
```
won't work if you specifiy a whitelist. So whitelist only.

See https://github.com/mvo5/unattended-upgrades/blob/master/README.md for more info.

**Comment by bitwombat** [comment]
Can you please elaborate on the downside? I read the README and don't understand the interaction between Package-Whitelist and Allowed-Origins.
