### ISSUE TITLE
Does not send email when package has conffile prompt and needs manual upgrade

### ISSUE THREAD

**Issue by Yvan-Masson** [mvo5/unattended-upgrades#89]
Hi,

I am using version 0.93.1+nmu1 on Raspbian Stretch. My version is a bit old but if I am not wrong upstream changelog does not mention a fix for my issue.

I have unattended-upgrades configured to send an email only when an error occurs. However, it does not send an email when an update has a conffile prompt and thus needs manual upgrade. This seems to be an important bug to me, because the administrator believes his system is up to date while it is not.

This was working "before" (see for example 0.86 changelog). I reported this bug with details in [Debian #852465](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=852465). Do not hesitate to ask if I can provide more information or test things.

Thanks for your work,
Yvan

**Comment by nomis** [comment]
The mail code checks for `^WARNING:` in `mem_log`, but it looks like `mem_log` will be formatted with timestamps and look like "(asctime) WARNING (message)".

The test code doesn't call the real logging code so it has no chance of verifying if this works properly or not.

**Comment by nomis** [comment]
The log level isn't even added to the `mem_log` log text, so there's no way to track warnings based on log messages.
